model:
  base_learning_rate: 4.5e-6
  target: src.models.autoencoder.PoseAutoencoder
  params:
    monitor: "val/rec_loss"
    embed_dim: 16
    euler_convention: "XYZ"
    activation: "relu"
    lossconfig:
      target: src.modules.losses.PoseLoss
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5
        pose_weight: 160
        class_weight: 0.0
        bbox_weight: 0.0
        pose_loss_fn: "l2"
        mask_weight: 25000
        mask_loss_fn: "l2"
        disc_in_channels: 4
        num_classes: 1
    pose_decoder_config:
      target: src.modules.autoencodermodules.pose_decoder.PoseDecoderSpatialVAE
      params: 
        num_classes: 1
        num_channels: 16
        n: 16
        m: 16
        hidden_dim: 500
        num_layers: 2
        activation: tanh
        resid: False
    
    pose_encoder_config:
      target: src.modules.autoencodermodules.pose_encoder.PoseEncoderSpatialVAE
      params:
        num_classes: 1
        num_channels: 16
        n: 16
        m: 16
        hidden_dim: 500
        num_layers: 2
        activation: swish
    ddconfig:
      double_z: True
      z_channels: 16
      resolution: 64
      in_channels: 3
      out_ch: 4
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

data:
  data_root: data/nuscenes
  target: src.data.preprocessing.data_modules.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 1
    wrap: True
    train:
      target: src.data.datasets.nuscenes.NuScenesTrain
      params:
        data_root: data/nuscenes
        pipeline: []
        box_type_3d: Camera
        load_type: frame_based
        modality: 
          use_camera: True 
          use_lidar: False
        filter_empty_gt: False
        test_mode: False
        with_velocity: False
        use_valid_flag: False
        label_names: ["car"]
        patch_height: 256
        patch_aspect_ratio: 1.0
    validation:
      target: src.data.datasets.nuscenes.NuScenesValidation
      params:
        data_root: data/nuscenes
        pipeline: []
        box_type_3d: Camera
        load_type: frame_based
        modality: 
          use_camera: True 
          use_lidar: False
        filter_empty_gt: False
        test_mode: False
        with_velocity: False
        use_valid_flag: False
        label_names: ["car"]
        patch_height: 256
        patch_aspect_ratio: 1.0

lightning:
  callbacks:
    image_logger:
      target: src.util.callbacks.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True
        disable_local_logging: False

    progress_bar:
      target: src.util.callbacks.TQDMProgressBar
      params:
        refresh_rate: 1
        process_position: 0

    device_stats_monitor:
      target: src.util.callbacks.DeviceStatsMonitor

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
    profiler: advanced
    max_epochs: 1000
    strategy: ddp
