model:
  base_learning_rate: 4.5e-6
  target: src.models.autoencoder.PoseAutoencoder
  params:
    monitor: "val/rec_loss"
    embed_dim: 4
    euler_convention: "XYZ"
    lossconfig:
      target: src.modules.losses.PoseLoss
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5
        pose_weight: 250000
        pose_loss_fn: "l2"
        mask_loss_weight: 0.5
        mask_loss_fn: "l2"
        disc_in_channels: 4

    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 64
      in_channels: 3
      out_ch: 4
      ch: 128
      ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0

data:
  data_root: data/processed/shapenet/processed_get3d
  target: src.data.preprocessing.data_modules.DataModuleFromConfig
  params:
    batch_size: 8
    wrap: True
    train:
      target: src.data.datasets.shapenet.ShapeNetPoseTrain
      params:
        size: 64
        euler_convention: "XYZ"
    validation:
      target: src.data.datasets.shapenet.ShapeNetPoseValidation
      params:
        size: 64
        euler_convention: "XYZ"

lightning:
  callbacks:
    image_logger:
      target: src.util.callbacks.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True
        disable_local_logging: False

    progress_bar:
      target: src.util.callbacks.TQDMProgressBar
      params:
        refresh_rate: 1
        process_position: 0

    device_stats_monitor: 
      target: src.util.callbacks.DeviceStatsMonitor

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
    profiler: pytorch
    max_epochs: 1000
